# Generated by Django 3.2.5 on 2023-06-22 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_spec'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='spec',
            field=models.CharField(max_length=255),
        ),
    ]
