# Generated by Django 3.2.5 on 2023-06-22 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_event_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='pic',
            field=models.ImageField(default='path/to/event-img/default.png', upload_to='path/to/event-img'),
        ),
    ]
